In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/kkbox-music-recommendation-challenge/test.csv.7z
/kaggle/input/kkbox-music-recommendation-challenge/train.csv.7z
/kaggle/input/kkbox-music-recommendation-challenge/songs.csv.7z
/kaggle/input/kkbox-music-recommendation-challenge/members.csv.7z
/kaggle/input/kkbox-music-recommendation-challenge/song_extra_info.csv.7z
/kaggle/input/kkbox-music-recommendation-challenge/sample_submission.csv.7z

In [ ]:
!pip install py7zr

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import py7zr
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

In [8]:
# Paths to the .7z files
file_paths = [
    "/kaggle/input/kkbox-music-recommendation-challenge/test.csv.7z",
    "/kaggle/input/kkbox-music-recommendation-challenge/train.csv.7z",
    "/kaggle/input/kkbox-music-recommendation-challenge/songs.csv.7z",
    "/kaggle/input/kkbox-music-recommendation-challenge/members.csv.7z",
    "/kaggle/input/kkbox-music-recommendation-challenge/song_extra_info.csv.7z",
    "/kaggle/input/kkbox-music-recommendation-challenge/sample_submission.csv.7z"
]

# Directory to extract CSV files
extracted_dir = "/kaggle/working/extracted_csv/"

# Create the directory if it doesn't exist
os.makedirs(extracted_dir, exist_ok=True)

# Extract each .7z file
for file_path in file_paths:
    with py7zr.SevenZipFile(file_path, mode='r') as z:
        z.extractall(path=extracted_dir)

print("Extraction complete.")

# List the extracted CSV files
extracted_files = os.listdir(extracted_dir)
csv_files = [file for file in extracted_files if file.endswith('.csv')]

print("Extracted CSV files:")
print(csv_files)

Extraction complete.
Extracted CSV files:
['train.csv', 'song_extra_info.csv', 'members.csv', 'test.csv', 'songs.csv', 'sample_submission.csv']

In [9]:
test = pd.read_csv('/kaggle/working/extracted_csv/test.csv')
train = pd.read_csv('/kaggle/working/extracted_csv/train.csv')
songs = pd.read_csv('/kaggle/working/extracted_csv/songs.csv')
members = pd.read_csv('/kaggle/working/extracted_csv/members.csv')
song_extra_info = pd.read_csv('/kaggle/working/extracted_csv/song_extra_info.csv')
sample_submission = pd.read_csv('/kaggle/working/extracted_csv/sample_submission.csv')

In [42]:
train

,msno,song_id,source_system_tab,source_screen_name,source_type,target
0,FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg=,BBzumQNXUHKdEBOB7mAJuzok+IJA1c2Ryg/yzTF6tik=,explore,Explore,online-playlist,1
1,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,bhp/MpSNoqoxOIB+/l8WPqu6jldth4DIpCm3ayXnJqM=,my library,Local playlist more,local-playlist,1
2,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,JNWfrrC7zNN7BdMpsISKa4Mw+xVJYNnxXh3/Epw7QgY=,my library,Local playlist more,local-playlist,1
3,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,2A87tzfnJTSWqD7gIZHisolhe4DMdzkbd6LzO1KHjNs=,my library,Local playlist more,local-playlist,1
4,FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg=,3qm6XTZ6MOCU11x8FIVbAGH5l5uMkT3/ZalWG1oo2Gc=,explore,Explore,online-playlist,1
...,...,...,...,...,...,...
7377413,6xdFzPlrasIDD95mQWXVC3Bg4ptnGYtBl4ztVEZMddU=,VJTxizih/o28kXCbtPbIyWXScoXGvxyYtl6R+0YB5JM=,my library,Local playlist more,local-playlist,1
7377414,ZxbVmt3Kh/XOH+h58c2Kdj6SjFZk+wnUO006IgWzMQE=,z1mqaU9YOX7T/PFDvUoWozdFq7rC3KwaQP7nFVprjMI=,search,Search,song,0
7377415,ZxbVmt3Kh/XOH+h58c2Kdj6SjFZk+wnUO006IgWzMQE=,750RprmFfLV0bymtDH88g24pLZGVi5VpBAI300P6UOA=,search,Search,song,1
7377416,0aH4Hd3ziPSRHClRX8rkeOEaAG5EPPkW1mKGCdXEok0=,G8wgqObgeAMER/rVCIlgcNeQ8mm0CzF/GsxiMK8TTnA=,discover,Discover Genre,online-playlist,1
7377417,0aH4Hd3ziPSRHClRX8rkeOEaAG5EPPkW1mKGCdXEok0=,Ju0VGkjWeBUZCd7r5Az2hUImhMoWxWLUicOedsmvG0g=,discover,Discover Genre,online-playlist,1

In [35]:
max_index = train['song_id'].str.len().idxmax()

# Получим саму строку по найденному индексу
longest_string = train.loc[max_index, 'song_id']

print("Самая длинная строка в столбце:")
print(longest_string)

Самая длинная строка в столбце:
BBzumQNXUHKdEBOB7mAJuzok+IJA1c2Ryg/yzTF6tik=

In [10]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,accuracy_score
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
import xgboost as xgb
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [11]:
train_data = train.copy()
test_data = test.copy()
members_data = members.copy()
songs_data = songs.copy()
song_extra_info_data = song_extra_info.copy()

In [12]:
train_df = pd.merge(train_data, songs_data, on='song_id', how='left')
del songs_data


train_df = pd.merge(train_data, members_data, on='msno', how='left')
del members_data

In [13]:
def find_dirty_values(data):
    dtypes = pd.DataFrame(data.dtypes,columns=["Data Type"])
    dtypes["Unique Values"]=data.nunique().sort_values(ascending=True)
    dtypes["Null Values"]=data.isnull().sum()
    dtypes["% null Values"]=data.isnull().sum()/len(data)
    return dtypes.sort_values(by="Null Values" , ascending=False).style.background_gradient(cmap='YlOrRd',axis=0)

In [14]:
result = find_dirty_values(train_df)
result

In [15]:
def handling_missing_values(dataframe):
    cat_cols = dataframe.select_dtypes(include='O').columns
    num_cols = dataframe.select_dtypes(include=(np.number)).columns
    for col in cat_cols:
        dataframe[col] = dataframe[col].fillna('UnKnown')
    for col in num_cols:
        dataframe[col] = dataframe[col].interpolate(method='linear')
    return dataframe

In [16]:
train_df = handling_missing_values(train_df)

In [17]:
result = find_dirty_values(train_df)
result

In [18]:
date_cols = ['registration_init_time','expiration_date']
def date_formatting(date):
    date = str(date)
    date = f"{date[:4]}-{date[4:6]}-{date[6:]}"
    return date
def paring_date(dataframe,date):
    dataframe[date] = pd.to_datetime(dataframe[date])
    dataframe[f"{date}-day"] = dataframe[date].dt.day
    dataframe[f"{date}-month"] = dataframe[date].dt.month
    dataframe[f"{date}-year"] = dataframe[date].dt.year
    return dataframe

In [19]:
for col in date_cols:
    train_df[col] = train_df[col].apply(date_formatting)
    train_df = paring_date(train_df,col)

In [20]:
cat_cols = train_df.select_dtypes(include="O").columns
encoder = LabelEncoder()
for col in cat_cols:
    
    train_df[col] = encoder.fit_transform(train_df[col])

In [21]:
x = train_df.drop(columns={"registration_init_time","expiration_date","song_id","msno"})
x.head()

,source_system_tab,source_screen_name,source_type,target,city,bd,gender,registered_via,registration_init_time-day,registration_init_time-month,registration_init_time-year,expiration_date-day,expiration_date-month,expiration_date-year
0,2,7,7,1,1,0,0,7,2,1,2012,5,10,2017
1,4,8,5,1,13,24,1,9,25,5,2011,11,9,2017
2,4,8,5,1,13,24,1,9,25,5,2011,11,9,2017
3,4,8,5,1,13,24,1,9,25,5,2011,11,9,2017
4,2,7,7,1,1,0,0,7,2,1,2012,5,10,2017

In [22]:
y = x.pop('target')

In [23]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.3,random_state=42)

In [ ]:
lr = LogisticRegression(max_iter=300,C=0.001,penalty="l2")
lr.fit(x_train,y_train)
train_pred = lr.predict(x_train)
test_pred = lr.predict(x_test)
lr_train_acc = accuracy_score(y_train,train_pred)
lr_test_acc = accuracy_score(y_test,test_pred)
print("Training Accuracy : ",lr_train_acc)
print("Test Accuracy : ",lr_test_acc)
print("Classification Report:\n",classification_report(y_train,train_pred))

In [ ]:
NB = GaussianNB(var_smoothing=0.01)
NB.fit(x_train,y_train)
train_pred = NB.predict(x_train)
test_pred = NB.predict(x_test)
NB_train_acc = accuracy_score(y_train,train_pred)
NB_test_acc = accuracy_score(y_test,test_pred)
print("Training Accuracy : ",NB_train_acc)
print("Test Accuracy : ",NB_test_acc)
print("Classification Report:\n",classification_report(y_train,train_pred))

In [24]:
Dtree = DecisionTreeClassifier(max_depth=None,min_samples_leaf=1,min_samples_split=5)
Dtree.fit(x_train,y_train)
train_pred = Dtree.predict(x_train)
test_pred = Dtree.predict(x_test)
Dtree_train_acc = accuracy_score(y_train,train_pred)
Dtree_test_acc = accuracy_score(y_test,test_pred)
print("Training Accuracy : ",Dtree_train_acc)
print("Test Accuracy : ",Dtree_test_acc)
print("Classification Report:\n",classification_report(y_train,train_pred))

Training Accuracy :  0.7318811926434958
Test Accuracy :  0.7133510088892865
Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.74      0.73   2564524
           1       0.74      0.72      0.73   2599668

    accuracy                           0.73   5164192
   macro avg       0.73      0.73      0.73   5164192
weighted avg       0.73      0.73      0.73   5164192

In [ ]:
gb = GradientBoostingClassifier(learning_rate=.1,max_depth=4,n_estimators=50)
gb.fit(x_train,y_train)
train_pred = gb.predict(x_train)
test_pred = gb.predict(x_test)
gb_train_acc = accuracy_score(y_train,train_pred)
gb_test_acc = accuracy_score(y_test,test_pred)
print("Training Accuracy : ",gb_train_acc)
print("Test Accuracy : ",gb_test_acc)
print("Classification Report:\n",classification_report(y_train,train_pred))

In [ ]:
xg = xgb.XGBClassifier(random_state=0,learning_rate=.01,max_depth=3,n_estimators=50)
xg.fit(x_train,y_train)
train_pred = xg.predict(x_train)
test_pred = xg.predict(x_test)
xg_train_acc = accuracy_score(y_train,train_pred)
xg_test_acc = accuracy_score(y_test,test_pred)
print("Training Accuracy : ",xg_train_acc)
print("Test Accuracy : ",xg_test_acc)
print("Classification Report:\n",classification_report(y_train,train_pred))

In [ ]:
cols = [
    ["Logistic Regression",lr_train_acc,lr_test_acc],
    ["Naive Bayes",NB_train_acc,NB_test_acc],
    ["Decision Trees",Dtree_train_acc,Dtree_test_acc],
    ["Gradient Boosting",gb_train_acc,gb_test_acc],
    ["XGBoost",xg_train_acc,xg_test_acc]
    ]
results = pd.DataFrame( cols,
                       columns = ["Model","Training Accuracy %","Test Evaluation %"]).sort_values(
                        by="Test Evaluation %",ascending=False)
results.style.background_gradient(cmap='Set1')

In [ ]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors


# Создание модели KNN с 20 ближайшими соседями
knn = NearestNeighbors(n_neighbors=20)
knn.fit(x)

# Пример поиска ближайших соседей для первой записи в датасете
query = x.iloc[[0]]
distances, indices = knn.kneighbors(query)

# Вывод song_id 20 ближайших соседей
print("20 ближайших соседей для первой записи:")
print(train_df.iloc[indices[0]])

In [47]:
indices

array([[    4, 17768, 14963, 17769, 14965,  9408,  9406, 17770,  6724,
         9407,     7,     5,     0,  6721, 14962, 17771,  6722,  6725,
         9409,  6723]])

In [46]:
print(train.iloc[indices[0]]['song_id'])

4        3qm6XTZ6MOCU11x8FIVbAGH5l5uMkT3/ZalWG1oo2Gc=
17768    NOZGiW7PvfAlCrlciaZpmYMpXM8OiJMnLjqUfna7vQM=
14963    yPMxRWxhG2gZj2BV1mzTW/faIoigIh1F9gWtXBslIOg=
17769    IKMFuL0f5Y8c63Hg9BXkeNJjE0z8yf3gMt/tOxF4QNE=
14965    e8qPmXjLP6RwXiYsrQB2Z3gRSS34LNCoYFR7iYznvOs=
9408     nt4dYk1vQyKPzun5YtaRpLB9xWOWIU3QKiZV3aTOJYs=
9406     NWrFxxzjzsSolyGnnLWlkRrMUIzbxhKesaJHNOp8e80=
17770    81mK2AN53Wxo7lKT15YL1lcCYdwmuZ/cSnmDiuwG+Uc=
6724     rdNg0FiLBStCei8h1/h2kwv8IS97ZgONQkb/kXGAvqM=
9407     eY3mod6Vs39GLjL86RwYG+6jDkjYUB5AGjbPEuqJmQM=
7        bPIvRTzfHxH5LgHrStll+tYwSQNVV8PySgA3M1PfTgc=
5        3Hg5kugV1S0wzEVLAEfqjIV5UHzb7bCrdBRQlGygLvU=
0        BBzumQNXUHKdEBOB7mAJuzok+IJA1c2Ryg/yzTF6tik=
6721     XUz4Z4wPPChz+OIwkwj7HJ8teIjW3rEMdEATM80rDxM=
14962    EUEMfptvZVeqhSQI6PzZeE/dX34a4fE1AnbJNyuDPjk=
17771    p9Vg2zk7w856BnMwxQYfqHp/DR7T+8TLqA6ZdA7s+MA=
6722     +h+uIXLQyXHuCdwAY5oT3T302vt0IdQJtux0APXhriw=
6725     WRuHbl8CJbAuzUb4f/88Ly6IXif+IVVWolkp33Nm8wI=
9409     BnjOmObP+8X8Yxk3tPHy1309L++jhPWBFD8QXCYJsT4=
6723     +LztcJcPEEwsikk6+K5udm06XJQMzR4+lzavKLUyE0k=
Name: song_id, dtype: object

In [ ]:
from sklearn.metrics import ndcg_score

# Предположим, у вас есть список рекомендаций и соответствующие релевантности
# Релевантности должны быть отсортированы по убыванию
relevances = [[3, 2, 3, 0, 1, 2]]  # список списков, где каждый внутренний список содержит релевантности для одного пользователя
k = 20 # число рекомендаций для рассчета метрики NDCG@k

ndcg = ndcg_score(relevances, k=k)

print("NDCG@{}: {:.4f}".format(k, ndcg))